title: Lê Tâm Như
description: Sinh viên năm nhất ngành Khoa học máy tính, HUTECH
email: letamnhu.291945@gmail.com
github_username: letamnhu492
author: Lê Tâm Như

theme: jekyll-theme-cayman
lang: vi

markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - .gitignore
